# Dataset Configuration
dataset:
  root_path: "/home/edramos/Documents/datasets/Strawberry-segmentation-synthetic"
  train_split: "train"
  val_split: "valid"
  test_split: "test"
  num_classes: 8
  class_names:
    - "Background"
    - "Angular Leafspot"
    - "Anthracnose Fruit Rot"
    - "Blossom Blight"
    - "Gray Mold"
    - "Leaf Spot"
    - "Powdery Mildew Fruit"
    - "Powdery Mildew Leaf"

# Model Configuration
model:
  name: "deeplabv3plus"
  encoder: "resnet50"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 8
  activation: "softmax"

# Training Configuration
training:
  batch_size: 8
  num_epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: "cosine"
  warmup_epochs: 5
  early_stopping_patience: 15

# Data Augmentation
augmentation:
  train:
    horizontal_flip: 0.5
    vertical_flip: 0.3
    random_rotate: 0.3
    random_brightness_contrast: 0.2
    random_gamma: 0.2
    blur: 0.1
    noise: 0.1
    elastic_transform: 0.1
  val:
    horizontal_flip: 0.0
    vertical_flip: 0.0

# Loss Configuration
loss:
  name: "dice_ce"
  dice_weight: 0.5
  ce_weight: 0.5

# Optimization
optimizer:
  name: "adamw"
  lr: 0.001
  weight_decay: 0.0001

# Scheduler
scheduler:
  name: "cosine"
  warmup_epochs: 5
  min_lr: 0.00001

# Logging
logging:
  log_dir: "logs"
  tensorboard: true
  wandb: false
  wandb_project: "strawberry-segmentation"
  save_frequency: 10

# Export Configuration
export:
  onnx_path: "models/model.onnx"
  tensorrt_path: "models/model.trt"
  input_shape: [1, 3, 512, 512]
  dynamic_batch: true
  fp16: true

# Hardware
hardware:
  device: "cuda"
  num_workers: 4
  pin_memory: true
  mixed_precision: true 